"use client";

import { useEffect, useRef, useMemo } from "react";
import { createRoot } from "react-dom/client";
import {
    InstructionCycleSimulator, VonNeumannArchitecture, ComputerEvolutionTimeline, SystemLayersVisualization,
    PythonInterpreterFlow, PythonObjectVisualizer, UnicodeEncodingVisualizer, ListResizingVisualizer,
    IntegerMemoryLayout, HashTableVisualizer, FunctionCallStackVisualizer, DecoratorExecutionFlow,
    GeneratorStateVisualizer, ExceptionHierarchyTree, ComputationalGraph, SequentialFlowVisualizer,
    BatchProcessor, TrainingSimulator, CheckpointSimulator, ProfilerVisualizer, AttentionMatrixVisualizer,
    ParallelVisualizer, QuantizationVisualizer, DistributedVisualizer, KernelFusionVisualizer,
    DispatcherVisualizer, TensorBroadcastingVisualizer, TensorStorageVisualizer, ActivationVisualizer,
    SamplerVisualizer, OptimizerPathVisualizer, TransferLearningVisualizer, TrainingDynamicsVisualizer,
    ConvolutionVisualizer, HookVisualizer, TorchScriptVisualizer, StridedMemoryVisualizer, CUDAStreamVisualizer,
    // Transformers Components
    TransformersEcosystemComparison, HuggingFaceEcosystemMap, VersionCompatibilityMatrix,
    PipelineFlowVisualizer, GenerationParametersExplorer, TopKTopPVisualizer,
    NERVisualizer, QuestionAnsweringVisualizer, PipelinePerformanceAnalyzer,
    TokenizationVisualizer, TokenAlgorithmComparison, AttentionMaskBuilder,
    ArchitectureExplorer, ConfigEditor, ModelOutputInspector,
    ModelRepoStructureExplorer, CacheManagementVisualizer, PipelineInternalFlow,
    DatasetPipeline, DataCollatorDemo, TrainingLoopVisualizer,
    TrainingArgumentsExplorer, MixedPrecisionComparison, TrainingStepBreakdown,
    CallbackFlow, LearningRateScheduler, TrainingMetricsPlot,
    // Chapter 6-7
    PEFTMethodComparison, LoRAMatrixDecomposition, LoRARankSelector,
    QLoRAQuantizationFlow, NF4DataTypeVisualizer, AdaLoraRankEvolution,
    MemoryOptimizationComparison, PrecisionFormatComparison, FloatFormatBitLayout,
    MixedPrecisionTrainingFlow, QuantizationProcessVisualizer, GradientAccumulationVisualizer,
    PTQMethodComparison,
    // Chapter 8 Distributed Training
    DistributedTrainingNeedVisualizer, ParallelismStrategyComparison, DDPCommunicationFlow,
    FSDPShardingVisualizer, DeepSpeedZeROStages, PipelineParallelismVisualizer,
    TensorParallelismVisualizer,
    // Chapter 9 Inference Optimization
    InferenceMetricsVisualizer, KVCacheMechanismVisualizer, FlashAttentionIOComparison,
    TorchCompileSpeedupChart, PagedAttentionVisualizer, SpeculativeDecodingFlow,
    DeploymentStackComparison,
    // Chapter 10 QLoRA
    QLoRAInnovationTimeline, NF4EncodingVisualizer, DoubleQuantizationFlow,
    PagedOptimizerVisualizer, LoRATargetModulesSelector, QLoRAMemoryOptimizationComparison,
    PEFTMethodComparisonTable,
    // Chapter 11 Mixed Precision Training
    FloatFormatComparison, AMPWorkflow, GradScalerVisualizer,
    FP16vsBF16Comparison, TensorCorePerformance, MixedPrecisionBenchmark,
    TrainingStabilityComparison,
    // Chapter 12 Post-Training Quantization
    PTQvsQATComparison, QuantizationGranularityVisualizer, GPTQAlgorithmFlow,
    GPTQvsBitsAndBytesComparison, AWQChannelProtection, PerplexityComparisonChart,
    QuantizationThroughputComparison, QuantizationMethodSummaryTable,
    // Chapter 13 Gradient Checkpointing
    MemoryBreakdownInteractive, GradientCheckpointingFlow, OptimizationCombinator,
    // Chapter 14 Accelerate
    AccelerateWorkflow, DistributedCommunicationVisualizer,
    // Chapter 15 FSDP
    ZeROStagesComparison, AllGatherReduceScatter,
    // Chapter 16 DeepSpeed
    ZeROStageDecisionTree, DeepSpeedOffloadFlow, ThreeDParallelismDiagram,
    // Chapter 17 Inference Optimization
    InferenceLatencyBreakdown, KVCacheComparisonVisualizer,
    // Chapter 18 vLLM & TGI
    PagedAttentionMemoryVisualizer, ContinuousBatchingDemo, InferenceFrameworkComparison,
    // Chapter 19 Speculative Decoding
    SpeculativeDecodingFlowVisualizer, MQAvsGQAComparison,
    // Chapter 20 Model Export
    SafetensorsVsPickleComparison, TorchScriptModeComparison, OperatorFusionVisualizer,
    // Chapter 21 Optimum
    OptimumBackendEcosystem, QuantizationWorkflowVisualizer,
    // Chapter 22 API & Docker Deployment
    RequestQueueVisualizer, K8sDeploymentVisualizer,
    // Chapter 23 Attention Mechanisms
    AttentionWeightHeatmap, MaskBuilder, PositionEncodingVisualizer, KVCacheDynamics,
    // Chapter 24 Custom Model Development
    ModelBuilderTool, CustomAttentionComparator,
    // Chapter 25 Custom Trainer
    TrainerHookFlow, LossFunctionExplorer,
    // Chapter 26 Multimodal Models
    MultimodalArchitecture, VisionEncoderVisualizer,
    // Chapter 28 Frontier Research
    LongContextStrategies, MoERouting, AttentionPatternAnalyzer,
    // Missing components - Chapter 0-1
    TaskTypeGallery, ZeroShotClassificationDemo, TaskInferenceFlowchart,
    // Missing components - PEFT & Quantization  
    LoRAMemoryAccuracyTradeoff, FSDPScalingChart,
    // Placeholder components

    QuantizationMethodComparison, QuantizationMethodsComprehensiveComparison,
    PerTensorVsPerChannelQuant, NF4vsINT4Comparison, DistributedMixedPrecision,
    AccelerateWorkflowVisualizer, AcceleratorAPIDemo, ThreeDParallelismVisualizer,
    CollectiveCommunicationPrimitives, TGIArchitectureDiagram, ModelExportDecisionTree,
    BackendAutoSelector, OptimizationEffectComparison, ProfilerVisualizationDemo,
    PEFTTrainingSpeedComparison,
    // LangChain Components
    LangChainEcosystemMap, LangChainArchitectureFlow, RunnableProtocolVisualizer, PromptTemplateBuilder,
    MessageFlowDiagram, LegacyVsLCELComparison, ErrorHandlingFlow, ChainGraphVisualizer,
    RunnableCompositionFlow, ParallelExecutionDemo, StreamingVisualizer, AsyncPerformanceComparison,
    ChainOrchestrationDiagram, MapReduceVisualizer, RouterDecisionTree,
    FewShotExampleSelector, PromptComposer, HubBrowser,
    OutputParserFlow, StructuredOutputBuilder, ParsingErrorDemo,
    ToolCallingFlow, FunctionSchemaBuilder, ToolExecutionTimeline,
    MemoryEvolutionTimeline, MemoryTypeComparison, EntityMemoryGraph,
    // Chapter 10-11: Persistence & Optimization
    PersistenceBackendComparison, SessionLifecycleFlow, StateCheckpointVisualizer,
    TokenManagementDashboard, MemoryRetrievalPerformance, PrivacyComplianceFlow,
    // Chapter 12-13: RAG & Vector Stores
    RAGArchitectureDiagram, TextSplittingVisualizer, EmbeddingSpaceVisualization,
    VectorStoreComparison, SimilaritySearchDemo, HybridRetrievalFlow,
    // Chapter 14-15: LangGraph & Agent Design
    LangGraphArchitectureDiagram, StateGraphExecution, CheckpointTimeline,
    AgentArchitectureComparison, ToolCallFlow, MultiAgentArchitecture,
    // Chapter 16: LangSmith Observability
    LangSmithTraceVisualization, EvaluationDashboard, MonitoringDashboard,
    // Chapter 17: LangServe Deployment
    LangServePlayground, DeploymentArchitecture, KubernetesArchitecture,
    // Chapter 18: Advanced RAG & Optimization
    AdvancedRAGComparison, QueryTransformationFlow, HybridSearchArchitecture,
    // Chapter 19: Production Engineering & Best Practices
    RetryFallbackFlow, PerformanceOptimizationDashboard, ProductionArchitectureDiagram,
    // Chapter 20: Multi-Agent Systems
    MultiAgentArchitectureComparison, SupervisorRoutingFlow, CollaborativeDebateFlow, MultiAgentCodeGenFlow,
    // Chapter 21: Planning & Reflection Agents
    PlanExecuteFlowDiagram, ReflectionLoopVisualizer, ErrorRecoveryFlowDiagram,
    // Chapter 22: LangSmith Tracing
    TraceTreeVisualizer, SpanTimelineChart, TokenUsageBreakdown,
    // Chapter 23: LangSmith Evaluation
    EvaluationPipeline, ABTestComparison, FeedbackDashboard,
    // Chapter 24: LangSmith Production Monitoring
    MonitoringDashboardReal, AlertRuleBuilder, CostAnalysisDashboard,
    // Chapter 25: LangServe Basics
    LangServeArchitecture, EndpointExplorer, RemoteRunnableDemo,
    // Chapter 26: LangServe Advanced Features
    AuthenticationFlow, RateLimitingVisualizer, MetricsDashboard,
    // Chapter 27: Deployment & Containerization
    DockerBuildFlow, CloudPlatformComparison, K8sArchitectureDiagram,
    // Chapter 28: Advanced Agent Patterns
    HumanInLoopFlow, LongTermMemoryArchitecture, ToolOrchestrationVisualizer,
    // Chapter 29: Ecosystem Integration
    FrameworkComparisonMatrix, MigrationPathGuide, APIMappingTable,
    // Chapter 30: Performance Optimization
    CachingStrategyComparison, CostOptimizationDashboard, ReliabilityDecisionTree,
    // Chapter 31: Security & Privacy
    PromptInjectionDefense, PIIDetectionFlow, SecurityAuditDashboard,
    // Chapter 32: Large-Scale Architecture
    MicroserviceArchitecture, ModelRoutingFlow, ABTestDashboard,
    // Chapter 33: Future Research
    SpeculativeDecodingFlow as SpeculativeDecodingFlowLangChain, MultimodalMemoryGraph, PluginEcosystemMap,
    // Reinforcement Learning Components
    RLEcosystemMap, AgentEnvironmentLoop, RLTimelineEvolution,
    MDPGraphVisualizer, BellmanEquationDerivation, ValueFunctionEvolution,
    PolicyIterationVisualizer, ValueIterationConvergence, GPIFramework,
    MCReturnEstimation, ImportanceSamplingVisualizer, OnPolicyVsOffPolicy,
    TDUpdateVisualizer, SARSAvsQLearning, MaximizationBiasDemo, NStepReturnComparison,
    EligibilityTraceEvolution, LambdaReturnWeighting, ForwardVsBackwardView,
    FunctionApproximationComparison, FeatureEngineeringVisualizer, DeadlyTriadDemo, NeuralNetworkApproximation,
    DQNArchitecture, ExperienceReplayVisualizer, TargetNetworkUpdate, DuelingDQNDecomposition, PrioritizedReplayWeighting,
    PolicyGradientTheorem, REINFORCEVariance, BaselineEffect, ActorCriticArchitecture,
    AdvantageEstimation, GAEWeighting, A3CArchitecture, SharedNetworkVisualization,
    DeterministicPolicyVisualization, DDPGArchitecture, TD3Improvements, OUNoiseProcess,
    TrustRegionVisualization, KLConstraintEffect, MonotonicImprovement, ConjugateGradientProcess,
    PPOClipMechanism, RatioClippingEffect, PPOvsTRPO, MultiEpochUpdate,
    MaxEntropyFramework, SoftBellmanEquation, SACArchitecture, TemperatureEffect,
    ParameterSpaceVsPolicySpace, FisherInformationMatrix, NaturalGradientVisualization,
    DistributedRLArchitecture, IMPALAFlow, VTraceCorrection,
    ModelBasedVsModelFree, DynaArchitecture, WorldModelVisualization, DreamerRollout,
    ExplorationVsExploitation, CountBasedBonus, ICMArchitecture, RNDNovelty, GoExploreProcess,
    OptionsFramework, FeudalArchitecture, SkillDiscovery, MAXQDecomposition,
    IRLProblemVisualization, GAILArchitecture, RewardRecovery,
    BehavioralCloningProcess, DAggerIteration, DistributionShift,
    OfflineRLChallenge, OODActionProblem, CQLObjective, DecisionTransformerArchitecture,
    MultiTaskLearning, TransferLearningFlow, CurriculumProgression,
    MetaLearningConcept, MAMLInnerOuterLoop, TaskDistributionSampling, PEARLArchitecture,
    ParetoFrontVisualization, MultiObjectiveTradeoff, ScalarizationComparison,
    SafetyConstraintVisualization, SafeExplorationDemo, RobustPolicyComparison, CVaRRiskMeasure,
    MARLProblemVisualization, NashEquilibriumDemo, CTDEArchitecture, AgentCommunication,
    ValueDecompositionComparison, QMIXMixingNetwork, MAPPOArchitecture, MeanFieldApproximation,
    SelfPlayEvolution, PopulationDiversity, LeagueTrainingArchitecture, EmergentBehaviorDemo,
    CooperativeTaskVisualization, RoleAssignment, SMACEnvironment,
    ZeroSumGameVisualization, ExploitabilityMeasure, CFRAlgorithm, MixedStrategyNash,
    RLHFPipeline, BradleyTerryModel, RewardModelTraining, KLPenaltyEffect, RewardHackingDemo,
    DPOvsRLHF, ImplicitRewardVisualization, IterativeDPOLoop, DPOLossLandscape,
    ReasoningTimeScaling, ProcessVsOutcomeReward, MCTSForReasoning, SelfVerificationLoop, ComputePerformanceTradeoff,
    ReActFramework, ToolSelectionProcess, AgentPlanningTree, MultiStepExecution,
    AlignmentTaxVisualization, EfficientRLHFComparison, CarbonFootprintTracker,
    ConvergenceProofVisualization, RegretBoundsChart, ExplorationStrategiesComparison,
    DistributionShiftVisualization, AdversarialAttackDemo, UncertaintyQuantification, PolicyExplainability,
    HyperparameterSensitivity, LearningCurveComparison, AblationStudyVisualizer, BenchmarkLeaderboard,
    DeploymentPipeline, OnlineLearningArchitecture, RLMonitoringDashboard, ToolchainComparison,
    FoundationModelsRL, EmbodiedAIDemo, OpenWorldExploration, FutureRoadmap,
    TileShapeSelectionGuide, TileLangEcosystemMap, ThreeLevelInterfaceDiagram,
    ThreeLevelInterfaceComparison, BeginnerVsDeveloperVsExpertCode,
    InterfacePerformanceComparison, TileAbstractionDiagram, ThreadBindingVisualizer,
    DataTypeHierarchy, MemoryHierarchyDiagram, AllocSharedVisualizer, AllocFragmentVisualizer,
    BankConflictDemo, MemoryLifecycleFlow, GEMMOptimizationPipeline, TilingStrategyVisualizer,
    SharedMemoryLayoutDemo, SoftwarePipeliningFlow, GEMMPerformanceComparison, LayoutInferenceFlow,
    SwizzledLayoutDemo, BankConflictComparison, LayoutPropagationVisualizer, SoftwarePipeliningDiagram,
    PipelineStageVisualizer, AsyncMemcpyFlow, RegisterPressureAnalyzer, PipeliningPerformanceChart,
    QuantizationSchemeComparison, DequantizeGEMMFlow, LowPrecisionPerformanceChart, INT8GEMMImplementation,
    FlashAttentionArchitecture, OnlineSoftmaxStep, IOAwareTilingDemo, FlashAttentionPerformanceComparison,
    SparseAttentionVisualizer, CausalMaskDemo, MLAArchitectureDiagram, FlashMLAImplementationFlow,
    KVCacheCompressionDemo, CodeLineComparison, MLAvsMHAvsGQAPerformance, TileLangIRToTensorIRFlow,
    BufferRegionDiagram, BlockLoopStructure, IRDumperVisualizer, TVMRelaxPipelineFlow,
    OperatorRegistrationDiagram, PassPipelineExplorer, CompilationStageVisualizer, OptimizationPassComparison,
    ThreadBindingDiagram, CUDAThreadMapping, AMDWavefrontMapping, AscendAICoreMapping,
    ThreadBindingPerformanceImpact, WarpShuffleVisualizer, WarpReduceDemo, TensorCoreMappingDiagram,
    WarpSpecializationFlow, NVIDIABackendArchitecture, PTXCodeGenerationFlow, TensorCoreInstructionMap,
    HopperFeatureDiagram, AMDGPUBackendArchitecture, MFMAInstructionMap, AMDvsNVIDIAComparison,
    EndToEndCompilationFlow, RelaxVMExecutionVisualizer, FullCompilationPipelineDiagram,
    AutoScheduleVsAutotuneComparison, ProfilingWorkflowDiagram, PerformanceMetricsDashboard,
    BottleneckClassificationChart, NCUAnalysisVisualizer, MemoryHierarchyPerformance, CoalescingAccessDemo,
    SharedMemoryOptimization, RegisterAllocationStrategy, BandwidthUtilizationChart,
    TensorCoreUtilizationChart, LoopUnrollingDemo, InstructionPipelineVisualizer, ComputeIntensityAnalyzer,
    OperatorFusionDiagram, FusionStrategyComparison, ProducerConsumerFusionFlow, FusionPerformanceChart,
    ConvolutionImplementationComparison, Im2ColTransformDemo, WinogradTransformFlow, ConvPerformanceBenchmark,
    ReductionPatternDiagram, TwoStageReductionFlow, LayerNormFusionDemo, ReductionPerformanceComparison,
    MoEArchitectureDiagram, ExpertGEMMScheduling, TokenDispatchFlow, MoESchedulingOptimization,
    MoEPerformanceAnalysis, TileLangVsTritonComparison, CodeComparisonGEMM, CodeComparisonFlashAttention,
    PerformanceCeilingChart, DeveloperExperienceComparison, CompilerArchitectureComparison, IRDesignComparison,
    SchedulingStrategyComparison, PerformanceBenchmarkMatrix, EcosystemComparisonChart,
    DeepSeekArchitectureOverview, FlashMLACompressionRatio, EndToEndPerformanceData,
    IndustrialKernelBenchmark, GEMMVsCuBLASChart, KernelDesignBestPractices, DebuggingWorkflowDiagram,
    IRDumpAnalyzer, ErrorPatternCatalog, TestingFrameworkArchitecture, SparsityTypeComparison,
    StructuredSparsityDemo, BlockSparseVisualizer, SparseVsDensePerformance, AgentAssistedCodeGen,
    HardwareSupportExpansion, EcosystemEvolutionDiagram, RepositoryStructureExplorer, BuildSystemFlow,
    TileLangTechStackOverview, TileLangVsTritonVsCUDAComparison,
    // ===== Computer Network Components =====
    InternetTimeline, AccessNetworkComparison, PacketVsCircuitSwitching, ISPHierarchy,
    PerformanceMetrics, LayerModelComparison, HubVsSwitch, ChapterSummary, ChapterSummaryQuiz,
    OSILayerInteractive, TCPIPModelInteractive, ModelComparison, ProtocolConceptInteractive,
    EncapsulationInteractive, OverheadCalculator, NICArchitecture, ProtocolStackImplementation,
    EncapsulationProcess, SignalParameterExplorer, BandwidthCalculator, DigitalEncodingVisualizer,
    ModulationSimulator, NyquistShannonCalculator, PhysicalLayerQuiz, EncodingExercise,
    FiberOpticsLab, TransceiverSimulator, CoaxialCableExplorer, AntennaPatternVisualizer,
    MultiplexingDemuxVisualizer, SONETFrameExplorer, FrequencySpectrumExplorer, CrosstalkVisualizer,
    DataLinkLayerOverview, FramingTechniques, CRCVisualizer, HammingCodeVisualizer,
    ARQComparison, CRCHardwareImplementation, HammingCodeCircuit, NICControllerArchitecture,
    StopAndWaitSimulator, GBNSimulator, SRSimulator, SlidingWindowConcept,
    SlidingWindowSimulator, ReliableTransferProtocolSimulator, ARQTimerDemo,
    ALOHASimulator, CSMAComparison, CSMA_CDSimulator, ChannelAllocationComparison,
    EthernetFrameParser, ARPDemo, ARPFlowDiagram, LearningBridgeDemo,
    STPSimulator, RSTPComparison, VLANSimulator, VLANTrunkDemo,
    VLANProcessorDemo, MACInMACDemo,
    IPv4HeaderParser, IPSubnetCalculator, IPFragmentationDemo, IPReassemblyDemo,
    NATSimulator, NATTableDemo, NATTraversalDemo, NAT64TranslationDemo,
    DHCPSimulator, DHCPPoolDemo, DijkstraDemo, DistanceVectorDemo,
    BGPDecisionDemo, LSDBDemo, RouteLookupDemo, ICMPMessageParser,
    CrossbarSchedulerDemo, BufferManagerDemo, TCAMSimulator,
    SDNControllerVisualizer, OpenFlowPipelineSimulator, P4PipelineVisualizer,
    NFVServiceChainVisualizer, SDNPerformanceAnalyzer, IntentBasedNetworkingDemo,
    InteractiveNetworkArchComparison,
    UDPDemo, UDPChecksumCalculator, UDPApplicationExplorer, UDPProgrammingPlayground,
    TCPSegmentVisualizer, TCPStateMachineVisualizer, TCPFlowDiagram,
    NagleAlgorithmDemo, SACKVisualizer, RTTEstimatorVisualizer,
    CongestionSimulator, CUBICVisualizer, TCPCongestionComparison, ECNVisualizer,
    AQMComparison, TimerWheelVisualizer, TCPKeepaliveDemo, TCPPerformanceDashboard,
    TCPResetAnalyzer, WindowScaleVisualizer,
    ConnectionIDSimulator, StreamMultiplexingDemo, QUICPacketFormatDemo,
    QUICEncryptionDemo, QUICTCPBenchmark, QUICCongestionDemo, QUICDeploymentChecklist,
    DNSRecordExplorer, DNSResolverFlow, DNSSECTrustChain, DNSCacheDemo,
    DNSLoadBalancerDemo, DNSMessageParser, DomainTreeExplorer, DoHDemo,
    HTTPMethodDemo, HTTPStatusCodeExplorer, HTTPHeaderExplorer, HTTPVersionComparison,
    HTTP2FrameDemo, HTTP3PerformanceChart, TLSHandshakeDemo, TLShandshakeengine, TLSKDFpipeline,
    EmailArchitectureDiagram, SMTPFlowDemo, IMAPvsPOP3Demo, MIMEDemo,
    MTARoutingDemo, SpamFilterDemo, EmailSecurityDemo, WebmailDemo,
    BitTorrentDemo, DHTDemo, PeerManagerDemo, CDNArchitectureDemo,
    P2PvsCSChart, DASHPlayerSimulator, LiveStreamingDemo, VideoCodecComparison,
    PythonSocketDemo, EpollDemo, ConcurrentServerDemo, ReactorDemo,
    HighPerfServerDemo, SocketLayerDiagram, SocketBufferVisualizer, ConnectionPoolDemo,
    BPFExplorer, PacketCaptureEngine, PortMuxSimulator,
    CIATriad, AESEncryptEngine, BlockCipherModes, RSAModularExponentiation,
    HMACConstruction, KeyManagementSystem, CertificateValidator,
    FirewallTCAMengine, IPsecSAengine, IDSDPIengine,
    ARPSpoofDetector, PortScannerSynEngine, SYNCookieDefense, TrafficAnalysisEngine,
    NetFlowCollector, NetworkFaultDiagnosticEngine,
    WiFiMACController, HandoverSimulation, CellularScheduler,
    OFDMModulator, CDMACodeVisualizer,
    MultimediaTrafficAnalyzer, WFQSchedulerSimulator, TokenBucketShaper,
    DiffServClassifier, RTPPacketParser, WebSocketDemo,
    NetworkDelaySimulator, BDPCalculator, BandwidthMeasurementEngine,
    QueuingSystemSimulator, NetworkEnvironmentSimulator, ProtocolPerformanceCalculator,
    ProtocolPerformanceSimulator, CacheStrategyDemo,
    IPv6HeaderParser, IPv6AddressConverter, NDPStateDiagram, SLAACProcessDiagram,
    IoTArchExplorer, MQTTQoSExplorer, LoRaRangeCalculator, EdgeSchedulerSimulator,
    IoTBatteryCalculator, SmartCityDashboard, FiveGSliceExplorer,
    MobileIPTunnelEngine, ZoneFileEditor,
    KnowledgeCheck, ABRDemo,
} from "@/components/interactive";



















interface ContentRendererProps {
    html: string;
    moduleId?: string;
}

const componentMap: Record<string, React.ComponentType> = {
    "InstructionCycleSimulator": InstructionCycleSimulator,
    "VonNeumannArchitecture": VonNeumannArchitecture,
    "ComputerEvolutionTimeline": ComputerEvolutionTimeline,
    "SystemLayersVisualization": SystemLayersVisualization,
    "PythonInterpreterFlow": PythonInterpreterFlow,
    "PythonObjectVisualizer": PythonObjectVisualizer,
    "UnicodeEncodingVisualizer": UnicodeEncodingVisualizer,
    "ListResizingVisualizer": ListResizingVisualizer,
    "IntegerMemoryLayout": IntegerMemoryLayout,
    "HashTableVisualizer": HashTableVisualizer,
    "FunctionCallStackVisualizer": FunctionCallStackVisualizer,
    "DecoratorExecutionFlow": DecoratorExecutionFlow,
    "GeneratorStateVisualizer": GeneratorStateVisualizer,
    "ExceptionHierarchyTree": ExceptionHierarchyTree,
    "ComputationalGraph": ComputationalGraph,
    "SequentialFlowVisualizer": SequentialFlowVisualizer,
    "BatchProcessor": BatchProcessor,
    "TrainingSimulator": TrainingSimulator,
    "CheckpointSimulator": CheckpointSimulator,
    "ProfilerVisualizer": ProfilerVisualizer,
    "AttentionMatrixVisualizer": AttentionMatrixVisualizer,
    "ParallelVisualizer": ParallelVisualizer,
    "QuantizationVisualizer": QuantizationVisualizer,
    "DistributedVisualizer": DistributedVisualizer,
    "KernelFusionVisualizer": KernelFusionVisualizer,
    "DispatcherVisualizer": DispatcherVisualizer,
    "TensorBroadcastingVisualizer": TensorBroadcastingVisualizer,
    "TensorStorageVisualizer": TensorStorageVisualizer,
    "ActivationVisualizer": ActivationVisualizer,
    "SamplerVisualizer": SamplerVisualizer,
    "OptimizerPathVisualizer": OptimizerPathVisualizer,
    "TransferLearningVisualizer": TransferLearningVisualizer,
    "TrainingDynamicsVisualizer": TrainingDynamicsVisualizer,
    "ConvolutionVisualizer": ConvolutionVisualizer,
    "HookVisualizer": HookVisualizer,
    "TorchScriptVisualizer": TorchScriptVisualizer,
    "StridedMemoryVisualizer": StridedMemoryVisualizer,
    "CUDAStreamVisualizer": CUDAStreamVisualizer,
    // Transformers Components
    "TransformersEcosystemComparison": TransformersEcosystemComparison,
    "HuggingFaceEcosystemMap": HuggingFaceEcosystemMap,
    "VersionCompatibilityMatrix": VersionCompatibilityMatrix,
    "PipelineFlowVisualizer": PipelineFlowVisualizer,
    "GenerationParametersExplorer": GenerationParametersExplorer,
    "TopKTopPVisualizer": TopKTopPVisualizer,
    "NERVisualizer": NERVisualizer,
    "QuestionAnsweringVisualizer": QuestionAnsweringVisualizer,
    "PipelinePerformanceAnalyzer": PipelinePerformanceAnalyzer,
    "TokenizationVisualizer": TokenizationVisualizer,
    "TokenAlgorithmComparison": TokenAlgorithmComparison,
    "AttentionMaskBuilder": AttentionMaskBuilder,
    "ArchitectureExplorer": ArchitectureExplorer,
    "ConfigEditor": ConfigEditor,
    "ModelOutputInspector": ModelOutputInspector,
    // Chapter 0 missing components
    "ModelRepoStructureExplorer": ModelRepoStructureExplorer,
    "CacheManagementVisualizer": CacheManagementVisualizer,
    "PipelineInternalFlow": PipelineInternalFlow,
    // Chapter 4-5 components
    "DatasetPipeline": DatasetPipeline,
    "DataCollatorDemo": DataCollatorDemo,
    "TrainingLoopVisualizer": TrainingLoopVisualizer,
    "TrainingArgumentsExplorer": TrainingArgumentsExplorer,
    "MixedPrecisionComparison": MixedPrecisionComparison,
    "TrainingStepBreakdown": TrainingStepBreakdown,
    "CallbackFlow": CallbackFlow,
    "LearningRateScheduler": LearningRateScheduler,
    "TrainingMetricsPlot": TrainingMetricsPlot,
    // Chapter 6 PEFT
    "PEFTMethodComparison": PEFTMethodComparison,
    "LoRAMatrixDecomposition": LoRAMatrixDecomposition,
    "LoRARankSelector": LoRARankSelector,
    "QLoRAQuantizationFlow": QLoRAQuantizationFlow,
    "NF4DataTypeVisualizer": NF4DataTypeVisualizer,
    "AdaLoraRankEvolution": AdaLoraRankEvolution,
    "MemoryOptimizationComparison": MemoryOptimizationComparison,
    // Chapter 7 Quantization
    "PrecisionFormatComparison": PrecisionFormatComparison,
    "FloatFormatBitLayout": FloatFormatBitLayout,
    "MixedPrecisionTrainingFlow": MixedPrecisionTrainingFlow,
    "QuantizationProcessVisualizer": QuantizationProcessVisualizer,
    "GradientAccumulationVisualizer": GradientAccumulationVisualizer,
    "PTQMethodComparison": PTQMethodComparison,
    // Chapter 8 Distributed Training
    "DistributedTrainingNeedVisualizer": DistributedTrainingNeedVisualizer,
    "ParallelismStrategyComparison": ParallelismStrategyComparison,
    "DDPCommunicationFlow": DDPCommunicationFlow,
    "FSDPShardingVisualizer": FSDPShardingVisualizer,
    "DeepSpeedZeROStages": DeepSpeedZeROStages,
    "PipelineParallelismVisualizer": PipelineParallelismVisualizer,
    "TensorParallelismVisualizer": TensorParallelismVisualizer,
    // Chapter 9 Inference Optimization
    "InferenceMetricsVisualizer": InferenceMetricsVisualizer,
    "KVCacheMechanismVisualizer": KVCacheMechanismVisualizer,
    "FlashAttentionIOComparison": FlashAttentionIOComparison,
    "TorchCompileSpeedupChart": TorchCompileSpeedupChart,
    "PagedAttentionVisualizer": PagedAttentionVisualizer,
    "SpeculativeDecodingFlow": SpeculativeDecodingFlow,
    "DeploymentStackComparison": DeploymentStackComparison,
    // Chapter 10 QLoRA
    "QLoRAInnovationTimeline": QLoRAInnovationTimeline,
    "NF4EncodingVisualizer": NF4EncodingVisualizer,
    "DoubleQuantizationFlow": DoubleQuantizationFlow,
    "PagedOptimizerVisualizer": PagedOptimizerVisualizer,
    "LoRATargetModulesSelector": LoRATargetModulesSelector,
    "QLoRAMemoryOptimizationComparison": QLoRAMemoryOptimizationComparison,
    "PEFTMethodComparisonTable": PEFTMethodComparisonTable,
    // Chapter 11 Mixed Precision Training
    "FloatFormatComparison": FloatFormatComparison,
    "AMPWorkflow": AMPWorkflow,
    "GradScalerVisualizer": GradScalerVisualizer,
    "FP16vsBF16Comparison": FP16vsBF16Comparison,
    "TensorCorePerformance": TensorCorePerformance,
    "MixedPrecisionBenchmark": MixedPrecisionBenchmark,
    "TrainingStabilityComparison": TrainingStabilityComparison,
    // Chapter 12 Post-Training Quantization
    "PTQvsQATComparison": PTQvsQATComparison,
    "QuantizationGranularityVisualizer": QuantizationGranularityVisualizer,
    "GPTQAlgorithmFlow": GPTQAlgorithmFlow,
    "GPTQvsBitsAndBytesComparison": GPTQvsBitsAndBytesComparison,
    "AWQChannelProtection": AWQChannelProtection,
    "PerplexityComparisonChart": PerplexityComparisonChart,
    "QuantizationThroughputComparison": QuantizationThroughputComparison,
    "QuantizationMethodSummaryTable": QuantizationMethodSummaryTable,
    // Chapter 13 Gradient Checkpointing
    "MemoryBreakdownInteractive": MemoryBreakdownInteractive,
    "GradientCheckpointingFlow": GradientCheckpointingFlow,
    "OptimizationCombinator": OptimizationCombinator,
    // Chapter 14 Accelerate
    "AccelerateWorkflow": AccelerateWorkflow,
    "DistributedCommunicationVisualizer": DistributedCommunicationVisualizer,
    // Chapter 15 FSDP
    "ZeROStagesComparison": ZeROStagesComparison,
    "AllGatherReduceScatter": AllGatherReduceScatter,
    // Chapter 16 DeepSpeed
    "ZeROStageDecisionTree": ZeROStageDecisionTree,
    "DeepSpeedOffloadFlow": DeepSpeedOffloadFlow,
    "ThreeDParallelismDiagram": ThreeDParallelismDiagram,
    // Chapter 17 Inference Optimization
    "InferenceLatencyBreakdown": InferenceLatencyBreakdown,
    "KVCacheComparisonVisualizer": KVCacheComparisonVisualizer,
    // Chapter 18 vLLM & TGI
    "PagedAttentionMemoryVisualizer": PagedAttentionMemoryVisualizer,
    "ContinuousBatchingDemo": ContinuousBatchingDemo,
    "InferenceFrameworkComparison": InferenceFrameworkComparison,
    // Chapter 19 Speculative Decoding
    "SpeculativeDecodingFlowVisualizer": SpeculativeDecodingFlowVisualizer,
    "MQAvsGQAComparison": MQAvsGQAComparison,
    // Chapter 20 Model Export
    "SafetensorsVsPickleComparison": SafetensorsVsPickleComparison,
    "TorchScriptModeComparison": TorchScriptModeComparison,
    "OperatorFusionVisualizer": OperatorFusionVisualizer,
    // Chapter 21 Optimum
    "OptimumBackendEcosystem": OptimumBackendEcosystem,
    "QuantizationWorkflowVisualizer": QuantizationWorkflowVisualizer,
    // Chapter 22 API & Docker Deployment
    "RequestQueueVisualizer": RequestQueueVisualizer,
    "K8sDeploymentVisualizer": K8sDeploymentVisualizer,
    // Chapter 23 Attention Mechanisms
    "AttentionWeightHeatmap": AttentionWeightHeatmap,
    "MaskBuilder": MaskBuilder,
    "PositionEncodingVisualizer": PositionEncodingVisualizer,
    "KVCacheDynamics": KVCacheDynamics,
    // Chapter 24 Custom Model Development
    "ModelBuilderTool": ModelBuilderTool,
    "CustomAttentionComparator": CustomAttentionComparator,
    // Chapter 25 Custom Trainer
    "TrainerHookFlow": TrainerHookFlow,
    "LossFunctionExplorer": LossFunctionExplorer,
    // Chapter 26 Multimodal Models
    "MultimodalArchitecture": MultimodalArchitecture,
    "VisionEncoderVisualizer": VisionEncoderVisualizer,
    // Chapter 28 Frontier Research
    "LongContextStrategies": LongContextStrategies,
    "MoERouting": MoERouting,
    "AttentionPatternAnalyzer": AttentionPatternAnalyzer,
    // Missing components - Chapter 0-1
    "TaskTypeGallery": TaskTypeGallery,
    "ZeroShotClassificationDemo": ZeroShotClassificationDemo,
    "TaskInferenceFlowchart": TaskInferenceFlowchart,
    // Missing components - PEFT & Quantization
    "LoRAMemoryAccuracyTradeoff": LoRAMemoryAccuracyTradeoff,
    "FSDPScalingChart": FSDPScalingChart,
    // Placeholder components
    "SpeculativeDecodingFlowLangChain": SpeculativeDecodingFlowLangChain,
    "MultimodalMemoryGraph": MultimodalMemoryGraph,
    "PluginEcosystemMap": PluginEcosystemMap,
    // Reinforcement Learning Components
    "RLEcosystemMap": RLEcosystemMap,
    "AgentEnvironmentLoop": AgentEnvironmentLoop,
    "RLTimelineEvolution": RLTimelineEvolution,
    "MDPGraphVisualizer": MDPGraphVisualizer,
    "BellmanEquationDerivation": BellmanEquationDerivation,
    "ValueFunctionEvolution": ValueFunctionEvolution,
    "PolicyIterationVisualizer": PolicyIterationVisualizer,
    "ValueIterationConvergence": ValueIterationConvergence,
    "GPIFramework": GPIFramework,
    "MCReturnEstimation": MCReturnEstimation,
    "ImportanceSamplingVisualizer": ImportanceSamplingVisualizer,
    "OnPolicyVsOffPolicy": OnPolicyVsOffPolicy,
    "TDUpdateVisualizer": TDUpdateVisualizer,
    "SARSAvsQLearning": SARSAvsQLearning,
    "MaximizationBiasDemo": MaximizationBiasDemo,
    "NStepReturnComparison": NStepReturnComparison,
    "EligibilityTraceEvolution": EligibilityTraceEvolution,
    "LambdaReturnWeighting": LambdaReturnWeighting,
    "ForwardVsBackwardView": ForwardVsBackwardView,
    "FunctionApproximationComparison": FunctionApproximationComparison,
    "FeatureEngineeringVisualizer": FeatureEngineeringVisualizer,
    "DeadlyTriadDemo": DeadlyTriadDemo,
    "NeuralNetworkApproximation": NeuralNetworkApproximation,
    "DQNArchitecture": DQNArchitecture,
    "ExperienceReplayVisualizer": ExperienceReplayVisualizer,
    "TargetNetworkUpdate": TargetNetworkUpdate,
    "DuelingDQNDecomposition": DuelingDQNDecomposition,
    "PrioritizedReplayWeighting": PrioritizedReplayWeighting,
    "PolicyGradientTheorem": PolicyGradientTheorem,
    "REINFORCEVariance": REINFORCEVariance,
    "BaselineEffect": BaselineEffect,
    "ActorCriticArchitecture": ActorCriticArchitecture,
    "AdvantageEstimation": AdvantageEstimation,
    "GAEWeighting": GAEWeighting,
    "A3CArchitecture": A3CArchitecture,
    "SharedNetworkVisualization": SharedNetworkVisualization,
    "DeterministicPolicyVisualization": DeterministicPolicyVisualization,
    "DDPGArchitecture": DDPGArchitecture,
    "TD3Improvements": TD3Improvements,
    "OUNoiseProcess": OUNoiseProcess,
    "TrustRegionVisualization": TrustRegionVisualization,
    "KLConstraintEffect": KLConstraintEffect,
    "MonotonicImprovement": MonotonicImprovement,
    "ConjugateGradientProcess": ConjugateGradientProcess,
    "PPOClipMechanism": PPOClipMechanism,
    "RatioClippingEffect": RatioClippingEffect,
    "PPOvsTRPO": PPOvsTRPO,
    "MultiEpochUpdate": MultiEpochUpdate,
    "MaxEntropyFramework": MaxEntropyFramework,
    "SoftBellmanEquation": SoftBellmanEquation,
    "SACArchitecture": SACArchitecture,
    "TemperatureEffect": TemperatureEffect,
    "ParameterSpaceVsPolicySpace": ParameterSpaceVsPolicySpace,
    "FisherInformationMatrix": FisherInformationMatrix,
    "NaturalGradientVisualization": NaturalGradientVisualization,
    "DistributedRLArchitecture": DistributedRLArchitecture,
    "IMPALAFlow": IMPALAFlow,
    "VTraceCorrection": VTraceCorrection,
    "ModelBasedVsModelFree": ModelBasedVsModelFree,
    "DynaArchitecture": DynaArchitecture,
    "WorldModelVisualization": WorldModelVisualization,
    "DreamerRollout": DreamerRollout,
    "ExplorationVsExploitation": ExplorationVsExploitation,
    "CountBasedBonus": CountBasedBonus,
    "ICMArchitecture": ICMArchitecture,
    "RNDNovelty": RNDNovelty,
    "GoExploreProcess": GoExploreProcess,
    "OptionsFramework": OptionsFramework,
    "FeudalArchitecture": FeudalArchitecture,
    "SkillDiscovery": SkillDiscovery,
    "MAXQDecomposition": MAXQDecomposition,
    "IRLProblemVisualization": IRLProblemVisualization,
    "GAILArchitecture": GAILArchitecture,
    "RewardRecovery": RewardRecovery,
    "BehavioralCloningProcess": BehavioralCloningProcess,
    "DAggerIteration": DAggerIteration,
    "DistributionShift": DistributionShift,
    "OfflineRLChallenge": OfflineRLChallenge,
    "OODActionProblem": OODActionProblem,
    "CQLObjective": CQLObjective,
    "DecisionTransformerArchitecture": DecisionTransformerArchitecture,
    "MultiTaskLearning": MultiTaskLearning,
    "TransferLearningFlow": TransferLearningFlow,
    "CurriculumProgression": CurriculumProgression,
    "MetaLearningConcept": MetaLearningConcept,
    "MAMLInnerOuterLoop": MAMLInnerOuterLoop,
    "TaskDistributionSampling": TaskDistributionSampling,
    "PEARLArchitecture": PEARLArchitecture,
    "ParetoFrontVisualization": ParetoFrontVisualization,
    "MultiObjectiveTradeoff": MultiObjectiveTradeoff,
    "ScalarizationComparison": ScalarizationComparison,
    "SafetyConstraintVisualization": SafetyConstraintVisualization,
    "SafeExplorationDemo": SafeExplorationDemo,
    "RobustPolicyComparison": RobustPolicyComparison,
    "CVaRRiskMeasure": CVaRRiskMeasure,
    "MARLProblemVisualization": MARLProblemVisualization,
    "NashEquilibriumDemo": NashEquilibriumDemo,
    "CTDEArchitecture": CTDEArchitecture,
    "AgentCommunication": AgentCommunication,
    "ValueDecompositionComparison": ValueDecompositionComparison,
    "QMIXMixingNetwork": QMIXMixingNetwork,
    "MAPPOArchitecture": MAPPOArchitecture,
    "MeanFieldApproximation": MeanFieldApproximation,
    "SelfPlayEvolution": SelfPlayEvolution,
    "PopulationDiversity": PopulationDiversity,
    "LeagueTrainingArchitecture": LeagueTrainingArchitecture,
    "EmergentBehaviorDemo": EmergentBehaviorDemo,
    "CooperativeTaskVisualization": CooperativeTaskVisualization,
    "RoleAssignment": RoleAssignment,
    "SMACEnvironment": SMACEnvironment,
    "ZeroSumGameVisualization": ZeroSumGameVisualization,
    "ExploitabilityMeasure": ExploitabilityMeasure,
    "CFRAlgorithm": CFRAlgorithm,
    "MixedStrategyNash": MixedStrategyNash,
    // Chapter 31: RLHF
    "RLHFPipeline": RLHFPipeline,
    "BradleyTerryModel": BradleyTerryModel,
    "RewardModelTraining": RewardModelTraining,
    "KLPenaltyEffect": KLPenaltyEffect,
    "RewardHackingDemo": RewardHackingDemo,
    // Chapter 32: DPO
    "DPOvsRLHF": DPOvsRLHF,
    "ImplicitRewardVisualization": ImplicitRewardVisualization,
    "IterativeDPOLoop": IterativeDPOLoop,
    "DPOLossLandscape": DPOLossLandscape,
    // Chapter 33: Reasoning-Time RL
    "ReasoningTimeScaling": ReasoningTimeScaling,
    "ProcessVsOutcomeReward": ProcessVsOutcomeReward,
    "MCTSForReasoning": MCTSForReasoning,
    "SelfVerificationLoop": SelfVerificationLoop,
    "ComputePerformanceTradeoff": ComputePerformanceTradeoff,
    // Chapter 34: LLM Agent
    "ReActFramework": ReActFramework,
    "ToolSelectionProcess": ToolSelectionProcess,
    "AgentPlanningTree": AgentPlanningTree,
    "MultiStepExecution": MultiStepExecution,
    // Chapter 35: Alignment Tax & Efficiency
    "AlignmentTaxVisualization": AlignmentTaxVisualization,
    "EfficientRLHFComparison": EfficientRLHFComparison,
    "CarbonFootprintTracker": CarbonFootprintTracker,
    // Chapter 36: RL Theory Foundations
    "ConvergenceProofVisualization": ConvergenceProofVisualization,
    "RegretBoundsChart": RegretBoundsChart,
    "ExplorationStrategiesComparison": ExplorationStrategiesComparison,
    // Chapter 37: Reliability & Robustness
    "DistributionShiftVisualization": DistributionShiftVisualization,
    "AdversarialAttackDemo": AdversarialAttackDemo,
    "UncertaintyQuantification": UncertaintyQuantification,
    "PolicyExplainability": PolicyExplainability,
    // Chapter 38: Hyperparameter Tuning
    "HyperparameterSensitivity": HyperparameterSensitivity,
    "LearningCurveComparison": LearningCurveComparison,
    "AblationStudyVisualizer": AblationStudyVisualizer,
    "BenchmarkLeaderboard": BenchmarkLeaderboard,
    // Chapter 39: Production Deployment
    "DeploymentPipeline": DeploymentPipeline,
    "OnlineLearningArchitecture": OnlineLearningArchitecture,
    "RLMonitoringDashboard": RLMonitoringDashboard,
    "ToolchainComparison": ToolchainComparison,
    // Chapter 40: Future Directions
    "FoundationModelsRL": FoundationModelsRL,
    "EmbodiedAIDemo": EmbodiedAIDemo,
    "OpenWorldExploration": OpenWorldExploration,
    "FutureRoadmap": FutureRoadmap,
    // TileLang Components
    "TileShapeSelectionGuide": TileShapeSelectionGuide,
    "TileLangEcosystemMap": TileLangEcosystemMap,
    "ThreeLevelInterfaceDiagram": ThreeLevelInterfaceDiagram,
    "ThreeLevelInterfaceComparison": ThreeLevelInterfaceComparison,
    "BeginnerVsDeveloperVsExpertCode": BeginnerVsDeveloperVsExpertCode,
    "InterfacePerformanceComparison": InterfacePerformanceComparison,
    "TileAbstractionDiagram": TileAbstractionDiagram,
    "ThreadBindingVisualizer": ThreadBindingVisualizer,
    "DataTypeHierarchy": DataTypeHierarchy,
    "MemoryHierarchyDiagram": MemoryHierarchyDiagram,
    "AllocSharedVisualizer": AllocSharedVisualizer,
    "AllocFragmentVisualizer": AllocFragmentVisualizer,
    "BankConflictDemo": BankConflictDemo,
    "MemoryLifecycleFlow": MemoryLifecycleFlow,
    "GEMMOptimizationPipeline": GEMMOptimizationPipeline,
    "TilingStrategyVisualizer": TilingStrategyVisualizer,
    "SharedMemoryLayoutDemo": SharedMemoryLayoutDemo,
    "SoftwarePipeliningFlow": SoftwarePipeliningFlow,
    "GEMMPerformanceComparison": GEMMPerformanceComparison,
    "LayoutInferenceFlow": LayoutInferenceFlow,
    "SwizzledLayoutDemo": SwizzledLayoutDemo,
    "BankConflictComparison": BankConflictComparison,
    "LayoutPropagationVisualizer": LayoutPropagationVisualizer,
    "SoftwarePipeliningDiagram": SoftwarePipeliningDiagram,
    "PipelineStageVisualizer": PipelineStageVisualizer,
    "AsyncMemcpyFlow": AsyncMemcpyFlow,
    "RegisterPressureAnalyzer": RegisterPressureAnalyzer,
    "PipeliningPerformanceChart": PipeliningPerformanceChart,
    "QuantizationSchemeComparison": QuantizationSchemeComparison,
    "DequantizeGEMMFlow": DequantizeGEMMFlow,
    "LowPrecisionPerformanceChart": LowPrecisionPerformanceChart,
    "INT8GEMMImplementation": INT8GEMMImplementation,
    "FlashAttentionArchitecture": FlashAttentionArchitecture,
    "OnlineSoftmaxStep": OnlineSoftmaxStep,
    "IOAwareTilingDemo": IOAwareTilingDemo,
    "FlashAttentionPerformanceComparison": FlashAttentionPerformanceComparison,
    "SparseAttentionVisualizer": SparseAttentionVisualizer,
    "CausalMaskDemo": CausalMaskDemo,
    "MLAArchitectureDiagram": MLAArchitectureDiagram,
    "FlashMLAImplementationFlow": FlashMLAImplementationFlow,
    "KVCacheCompressionDemo": KVCacheCompressionDemo,
    "CodeLineComparison": CodeLineComparison,
    "MLAvsMHAvsGQAPerformance": MLAvsMHAvsGQAPerformance,
    "TileLangIRToTensorIRFlow": TileLangIRToTensorIRFlow,
    "BufferRegionDiagram": BufferRegionDiagram,
    "BlockLoopStructure": BlockLoopStructure,
    "IRDumperVisualizer": IRDumperVisualizer,
    "TVMRelaxPipelineFlow": TVMRelaxPipelineFlow,
    "OperatorRegistrationDiagram": OperatorRegistrationDiagram,
    "PassPipelineExplorer": PassPipelineExplorer,
    "CompilationStageVisualizer": CompilationStageVisualizer,
    "OptimizationPassComparison": OptimizationPassComparison,
    "ThreadBindingDiagram": ThreadBindingDiagram,
    "CUDAThreadMapping": CUDAThreadMapping,
    "AMDWavefrontMapping": AMDWavefrontMapping,
    "AscendAICoreMapping": AscendAICoreMapping,
    "ThreadBindingPerformanceImpact": ThreadBindingPerformanceImpact,
    "WarpShuffleVisualizer": WarpShuffleVisualizer,
    "WarpReduceDemo": WarpReduceDemo,
    "TensorCoreMappingDiagram": TensorCoreMappingDiagram,
    "WarpSpecializationFlow": WarpSpecializationFlow,
    "NVIDIABackendArchitecture": NVIDIABackendArchitecture,
    "PTXCodeGenerationFlow": PTXCodeGenerationFlow,
    "TensorCoreInstructionMap": TensorCoreInstructionMap,
    "HopperFeatureDiagram": HopperFeatureDiagram,
    "AMDGPUBackendArchitecture": AMDGPUBackendArchitecture,
    "MFMAInstructionMap": MFMAInstructionMap,
    "AMDvsNVIDIAComparison": AMDvsNVIDIAComparison,
    "EndToEndCompilationFlow": EndToEndCompilationFlow,
    "RelaxVMExecutionVisualizer": RelaxVMExecutionVisualizer,
    "FullCompilationPipelineDiagram": FullCompilationPipelineDiagram,
    "AutoScheduleVsAutotuneComparison": AutoScheduleVsAutotuneComparison,
    "ProfilingWorkflowDiagram": ProfilingWorkflowDiagram,
    "PerformanceMetricsDashboard": PerformanceMetricsDashboard,
    "BottleneckClassificationChart": BottleneckClassificationChart,
    "NCUAnalysisVisualizer": NCUAnalysisVisualizer,
    "MemoryHierarchyPerformance": MemoryHierarchyPerformance,
    "CoalescingAccessDemo": CoalescingAccessDemo,
    "SharedMemoryOptimization": SharedMemoryOptimization,
    "RegisterAllocationStrategy": RegisterAllocationStrategy,
    "BandwidthUtilizationChart": BandwidthUtilizationChart,
    "TensorCoreUtilizationChart": TensorCoreUtilizationChart,
    "LoopUnrollingDemo": LoopUnrollingDemo,
    "InstructionPipelineVisualizer": InstructionPipelineVisualizer,
    "ComputeIntensityAnalyzer": ComputeIntensityAnalyzer,
    "OperatorFusionDiagram": OperatorFusionDiagram,
    "FusionStrategyComparison": FusionStrategyComparison,
    "ProducerConsumerFusionFlow": ProducerConsumerFusionFlow,
    "FusionPerformanceChart": FusionPerformanceChart,
    "ConvolutionImplementationComparison": ConvolutionImplementationComparison,
    "Im2ColTransformDemo": Im2ColTransformDemo,
    "WinogradTransformFlow": WinogradTransformFlow,
    "ConvPerformanceBenchmark": ConvPerformanceBenchmark,
    "ReductionPatternDiagram": ReductionPatternDiagram,
    "TwoStageReductionFlow": TwoStageReductionFlow,
    "LayerNormFusionDemo": LayerNormFusionDemo,
    "ReductionPerformanceComparison": ReductionPerformanceComparison,
    "MoEArchitectureDiagram": MoEArchitectureDiagram,
    "ExpertGEMMScheduling": ExpertGEMMScheduling,
    "TokenDispatchFlow": TokenDispatchFlow,
    "MoESchedulingOptimization": MoESchedulingOptimization,
    "MoEPerformanceAnalysis": MoEPerformanceAnalysis,
    "TileLangVsTritonComparison": TileLangVsTritonComparison,
    "CodeComparisonGEMM": CodeComparisonGEMM,
    "CodeComparisonFlashAttention": CodeComparisonFlashAttention,
    "PerformanceCeilingChart": PerformanceCeilingChart,
    "DeveloperExperienceComparison": DeveloperExperienceComparison,
    "CompilerArchitectureComparison": CompilerArchitectureComparison,
    "IRDesignComparison": IRDesignComparison,
    "SchedulingStrategyComparison": SchedulingStrategyComparison,
    "PerformanceBenchmarkMatrix": PerformanceBenchmarkMatrix,
    "EcosystemComparisonChart": EcosystemComparisonChart,
    "DeepSeekArchitectureOverview": DeepSeekArchitectureOverview,
    "FlashMLACompressionRatio": FlashMLACompressionRatio,
    "EndToEndPerformanceData": EndToEndPerformanceData,
    "IndustrialKernelBenchmark": IndustrialKernelBenchmark,
    "GEMMVsCuBLASChart": GEMMVsCuBLASChart,
    "KernelDesignBestPractices": KernelDesignBestPractices,
    "DebuggingWorkflowDiagram": DebuggingWorkflowDiagram,
    "IRDumpAnalyzer": IRDumpAnalyzer,
    "ErrorPatternCatalog": ErrorPatternCatalog,
    "TestingFrameworkArchitecture": TestingFrameworkArchitecture,
    "SparsityTypeComparison": SparsityTypeComparison,
    "StructuredSparsityDemo": StructuredSparsityDemo,
    "BlockSparseVisualizer": BlockSparseVisualizer,
    "SparseVsDensePerformance": SparseVsDensePerformance,
    "AgentAssistedCodeGen": AgentAssistedCodeGen,
    "HardwareSupportExpansion": HardwareSupportExpansion,
    "EcosystemEvolutionDiagram": EcosystemEvolutionDiagram,
    "RepositoryStructureExplorer": RepositoryStructureExplorer,
    "BuildSystemFlow": BuildSystemFlow,
    "TileLangTechStackOverview": TileLangTechStackOverview,
    "TileLangVsTritonVsCUDAComparison": TileLangVsTritonVsCUDAComparison,
    "ASTMappingDiagram": IRDumpAnalyzer,
    "ASTViewer": IRDumperVisualizer,
    "AdvancedControlFlow": SequentialFlowVisualizer,
    "AdvancedOpsPlayground": TensorBroadcastingVisualizer,
    "ArangeIndexVisualization": ThreadBindingVisualizer,
    "AutotuningDiagram": AutoScheduleVsAutotuneComparison,
    "AutotuningExplorer": AutoScheduleVsAutotuneComparison,
    "BankConflictVisualizer": BankConflictDemo,
    "BlockPointerAdvanceAnimation": BufferRegionDiagram,
    "BlockPointerMotivationDiagram": BufferRegionDiagram,
    "BlockPtrAdvanceAnim": BufferRegionDiagram,
    "BlockedEncodingMapper": ThreadBindingDiagram,
    "BroadcastingVisualizer": TensorBroadcastingVisualizer,
    "CacheBehaviorDiagram": MemoryHierarchyPerformance,
    "CoalescingVisualizer": CoalescingAccessDemo,
    "CompilationTimeline": CompilationStageVisualizer,
    "CompilerComparisonChart": CompilerArchitectureComparison,
    "ConditionalBranching": SequentialFlowVisualizer,
    "CudaTritonMappingDiagram": CUDAThreadMapping,
    "DebugConsole": DebuggingWorkflowDiagram,
    "DebuggingChecklist": ErrorPatternCatalog,
    "DependencyGraph": PassPipelineExplorer,
    "DivergenceAnalyzer": WarpSpecializationFlow,
    "DotOperandMapping": TensorCoreMappingDiagram,
    "DotOperationVisualizer": TensorCoreMappingDiagram,
    "EncodingBenchmark": PerformanceBenchmarkMatrix,
    "EncodingDebugger": IRDumpAnalyzer,
    "EncodingHierarchy": IRDesignComparison,
    "EncodingVisualizer": ThreadBindingDiagram,
    "EvictionPolicyDemo": CacheStrategyDemo,
    "FPFormatComparison": FloatFormatComparison,
    "FirstKernelInteractiveDemo": TileLangTechStackOverview,
    "FusedOperationDiagram": OperatorFusionDiagram,
    "GridDimensionSelector": ThreadBindingVisualizer,
    "GridStrideLoopAnimation": ThreadBindingPerformanceImpact,
    "IRConversionStep": FullCompilationPipelineDiagram,
    "IRDebuggingTools": IRDumpAnalyzer,
    "IRStageViewer": CompilationStageVisualizer,
    "InstallationComparisonTable": RepositoryStructureExplorer,
    "InstallationMethodSelector": BuildSystemFlow,
    "JITCompilationFlow": FullCompilationPipelineDiagram,
    "KernelLaunchComparison": CodeLineComparison,
    "KernelStructureDiagram": TileAbstractionDiagram,
    "LaunchParameterTuner": RegisterPressureAnalyzer,
    "LayoutConversionCost": LayoutPropagationVisualizer,
    "LayoutVisualizer": LayoutInferenceFlow,
    "LoadParameterExplorer": MemoryHierarchyPerformance,
    "LoadStoreVisualizer": MemoryHierarchyPerformance,
    "LoopUnrolling": LoopUnrollingDemo,
    "MaskedLoadVisualizer": CoalescingAccessDemo,
    "MaskingVisualization": CausalMaskDemo,
    "MatmulEncodingFlow": TensorCoreMappingDiagram,
    "MatmulMemoryAccess": MemoryHierarchyPerformance,
    "MatmulTilingVisualization": TilingStrategyVisualizer,
    "MemoryAccessPatternChart": BandwidthUtilizationChart,
    "MemoryHierarchyVisualizer": MemoryHierarchyDiagram,
    "MemoryOptimizationChecklist": KernelDesignBestPractices,
    "MultiDimIndexCalculator": ThreadBindingVisualizer,
    "NumericalStabilityExplorer": FloatFormatComparison,
    "OccupancyCalculator": RegisterPressureAnalyzer,
    "OnlineSoftmaxCodeWalkthrough": OnlineSoftmaxStep,
    "OnlineSoftmaxVisualization": OnlineSoftmaxStep,
    "PTXViewer": PTXCodeGenerationFlow,
    "PassPipelineVisualizer": PassPipelineExplorer,
    "PerformanceComparison": PerformanceBenchmarkMatrix,
    "PipelineVisualizer": SoftwarePipeliningDiagram,
    "ProgramIdVisualization": ThreadBindingVisualizer,
    "ReduceOperationDiagram": ReductionPatternDiagram,
    "ReductionPatternExplorer": ReductionPatternDiagram,
    "RepoDirectoryTree": RepositoryStructureExplorer,
    "RooflineVisualizer": ComputeIntensityAnalyzer,
    "SSAFormDiagram": IRDesignComparison,
    "SideBySideCodeComparison": CodeComparisonGEMM,
    "SoftmaxBenchmarkChart": PerformanceBenchmarkMatrix,
    "SoftmaxComputationFlow": OnlineSoftmaxStep,
    "SoftmaxStepByStep": OnlineSoftmaxStep,
    "SourceCodeBrowser": RepositoryStructureExplorer,
    "TLAPITable": TileLangTechStackOverview,
    "TargetPlatformTable": HardwareSupportExpansion,
    "TensorCoreLayout": TensorCoreMappingDiagram,
    "TensorCreationZeros": TensorStorageVisualizer,
    "TensorOpsVisualizer": TensorBroadcastingVisualizer,
    "TileAbstractionComparison": TileAbstractionDiagram,
    "TilePrimitivesTable": TileLangTechStackOverview,
    "TilingStrategyDiagram": TilingStrategyVisualizer,
    "TilingVisualizer": TilingStrategyVisualizer,
    "TritonApplications": IndustrialKernelBenchmark,
    "TritonDesignPhilosophy": TileLangVsTritonVsCUDAComparison,
    "TritonOriginTimeline": ComputerEvolutionTimeline,
    "TritonVsCUDATable": TileLangVsTritonVsCUDAComparison,
    "TypeCastingDiagram": DataTypeHierarchy,
    "TypePromotionChart": DataTypeHierarchy,
    "TypeSystemDiagram": DataTypeHierarchy,
    "WarpShuffleReduction": WarpReduceDemo,
    "WhereVsIfElse": SequentialFlowVisualizer,
    "blocked-layout-diagram": ThreadBindingDiagram,
    "dialect-lowering-diagram": FullCompilationPipelineDiagram,
    // ===== Computer Network Component Map =====
    "InternetTimeline": InternetTimeline,
    "AccessNetworkComparison": AccessNetworkComparison,
    "PacketVsCircuitSwitching": PacketVsCircuitSwitching,
    "ISPHierarchy": ISPHierarchy,
    "PerformanceMetrics": PerformanceMetrics,
    "LayerModelComparison": LayerModelComparison,
    "HubVsSwitch": HubVsSwitch,
    "ChapterSummary": ChapterSummary,
    "ChapterSummaryQuiz": ChapterSummaryQuiz,
    "OSILayerInteractive": OSILayerInteractive,
    "TCPIPModelInteractive": TCPIPModelInteractive,
    "ModelComparison": ModelComparison,
    "ProtocolConceptInteractive": ProtocolConceptInteractive,
    "EncapsulationInteractive": EncapsulationInteractive,
    "OverheadCalculator": OverheadCalculator,
    "NICArchitecture": NICArchitecture,
    "ProtocolStackImplementation": ProtocolStackImplementation,
    "EncapsulationProcess": EncapsulationProcess,
    "SignalParameterExplorer": SignalParameterExplorer,
    "BandwidthCalculator": BandwidthCalculator,
    "DigitalEncodingVisualizer": DigitalEncodingVisualizer,
    "ModulationSimulator": ModulationSimulator,
    "NyquistShannonCalculator": NyquistShannonCalculator,
    "PhysicalLayerQuiz": PhysicalLayerQuiz,
    "EncodingExercise": EncodingExercise,
    "FiberOpticsLab": FiberOpticsLab,
    "TransceiverSimulator": TransceiverSimulator,
    "CoaxialCableExplorer": CoaxialCableExplorer,
    "AntennaPatternVisualizer": AntennaPatternVisualizer,
    "MultiplexingDemuxVisualizer": MultiplexingDemuxVisualizer,
    "SONETFrameExplorer": SONETFrameExplorer,
    "FrequencySpectrumExplorer": FrequencySpectrumExplorer,
    "CrosstalkVisualizer": CrosstalkVisualizer,
    "DataLinkLayerOverview": DataLinkLayerOverview,
    "FramingTechniques": FramingTechniques,
    "CRCVisualizer": CRCVisualizer,
    "HammingCodeVisualizer": HammingCodeVisualizer,
    "ARQComparison": ARQComparison,
    "CRCHardwareImplementation": CRCHardwareImplementation,
    "HammingCodeCircuit": HammingCodeCircuit,
    "NICControllerArchitecture": NICControllerArchitecture,
    "StopAndWaitSimulator": StopAndWaitSimulator,
    "GBNSimulator": GBNSimulator,
    "SRSimulator": SRSimulator,
    "SlidingWindowConcept": SlidingWindowConcept,
    "SlidingWindowSimulator": SlidingWindowSimulator,
    "ReliableTransferProtocolSimulator": ReliableTransferProtocolSimulator,
    "ARQTimerDemo": ARQTimerDemo,
    "ALOHASimulator": ALOHASimulator,
    "CSMAComparison": CSMAComparison,
    "CSMA_CDSimulator": CSMA_CDSimulator,
    "ChannelAllocationComparison": ChannelAllocationComparison,
    "EthernetFrameParser": EthernetFrameParser,
    "ARPDemo": ARPDemo,
    "ARPFlowDiagram": ARPFlowDiagram,
    "LearningBridgeDemo": LearningBridgeDemo,
    "STPSimulator": STPSimulator,
    "RSTPComparison": RSTPComparison,
    "VLANSimulator": VLANSimulator,
    "VLANTrunkDemo": VLANTrunkDemo,
    "VLANProcessorDemo": VLANProcessorDemo,
    "MACInMACDemo": MACInMACDemo,
    "IPv4HeaderParser": IPv4HeaderParser,
    "IPSubnetCalculator": IPSubnetCalculator,
    "IPFragmentationDemo": IPFragmentationDemo,
    "IPReassemblyDemo": IPReassemblyDemo,
    "NATSimulator": NATSimulator,
    "NATTableDemo": NATTableDemo,
    "NATTraversalDemo": NATTraversalDemo,
    "NAT64TranslationDemo": NAT64TranslationDemo,
    "DHCPSimulator": DHCPSimulator,
    "DHCPPoolDemo": DHCPPoolDemo,
    "DijkstraDemo": DijkstraDemo,
    "DistanceVectorDemo": DistanceVectorDemo,
    "BGPDecisionDemo": BGPDecisionDemo,
    "LSDBDemo": LSDBDemo,
    "RouteLookupDemo": RouteLookupDemo,
    "ICMPMessageParser": ICMPMessageParser,
    "CrossbarSchedulerDemo": CrossbarSchedulerDemo,
    "BufferManagerDemo": BufferManagerDemo,
    "TCAMSimulator": TCAMSimulator,
    "SDNControllerVisualizer": SDNControllerVisualizer,
    "OpenFlowPipelineSimulator": OpenFlowPipelineSimulator,
    "P4PipelineVisualizer": P4PipelineVisualizer,
    "NFVServiceChainVisualizer": NFVServiceChainVisualizer,
    "SDNPerformanceAnalyzer": SDNPerformanceAnalyzer,
    "IntentBasedNetworkingDemo": IntentBasedNetworkingDemo,
    "InteractiveNetworkArchComparison": InteractiveNetworkArchComparison,
    "UDPDemo": UDPDemo,
    "UDPChecksumCalculator": UDPChecksumCalculator,
    "UDPApplicationExplorer": UDPApplicationExplorer,
    "UDPProgrammingPlayground": UDPProgrammingPlayground,
    "TCPSegmentVisualizer": TCPSegmentVisualizer,
    "TCPStateMachineVisualizer": TCPStateMachineVisualizer,
    "TCPFlowDiagram": TCPFlowDiagram,
    "NagleAlgorithmDemo": NagleAlgorithmDemo,
    "SACKVisualizer": SACKVisualizer,
    "RTTEstimatorVisualizer": RTTEstimatorVisualizer,
    "CongestionSimulator": CongestionSimulator,
    "CUBICVisualizer": CUBICVisualizer,
    "TCPCongestionComparison": TCPCongestionComparison,
    "ECNVisualizer": ECNVisualizer,
    "AQMComparison": AQMComparison,
    "TimerWheelVisualizer": TimerWheelVisualizer,
    "TCPKeepaliveDemo": TCPKeepaliveDemo,
    "TCPPerformanceDashboard": TCPPerformanceDashboard,
    "TCPResetAnalyzer": TCPResetAnalyzer,
    "WindowScaleVisualizer": WindowScaleVisualizer,
    "ConnectionIDSimulator": ConnectionIDSimulator,
    "StreamMultiplexingDemo": StreamMultiplexingDemo,
    "QUICPacketFormatDemo": QUICPacketFormatDemo,
    "QUICEncryptionDemo": QUICEncryptionDemo,
    "QUICTCPBenchmark": QUICTCPBenchmark,
    "QUICCongestionDemo": QUICCongestionDemo,
    "QUICDeploymentChecklist": QUICDeploymentChecklist,
    "DNSRecordExplorer": DNSRecordExplorer,
    "DNSResolverFlow": DNSResolverFlow,
    "DNSSECTrustChain": DNSSECTrustChain,
    "DNSCacheDemo": DNSCacheDemo,
    "DNSLoadBalancerDemo": DNSLoadBalancerDemo,
    "DNSMessageParser": DNSMessageParser,
    "DomainTreeExplorer": DomainTreeExplorer,
    "DoHDemo": DoHDemo,
    "HTTPMethodDemo": HTTPMethodDemo,
    "HTTPStatusCodeExplorer": HTTPStatusCodeExplorer,
    "HTTPHeaderExplorer": HTTPHeaderExplorer,
    "HTTPVersionComparison": HTTPVersionComparison,
    "HTTP2FrameDemo": HTTP2FrameDemo,
    "HTTP3PerformanceChart": HTTP3PerformanceChart,
    "TLSHandshakeDemo": TLSHandshakeDemo,
    "TLShandshakeengine": TLShandshakeengine,
    "TLSKDFpipeline": TLSKDFpipeline,
    "EmailArchitectureDiagram": EmailArchitectureDiagram,
    "SMTPFlowDemo": SMTPFlowDemo,
    "IMAPvsPOP3Demo": IMAPvsPOP3Demo,
    "MIMEDemo": MIMEDemo,
    "MTARoutingDemo": MTARoutingDemo,
    "SpamFilterDemo": SpamFilterDemo,
    "EmailSecurityDemo": EmailSecurityDemo,
    "WebmailDemo": WebmailDemo,
    "BitTorrentDemo": BitTorrentDemo,
    "DHTDemo": DHTDemo,
    "PeerManagerDemo": PeerManagerDemo,
    "CDNArchitectureDemo": CDNArchitectureDemo,
    "P2PvsCSChart": P2PvsCSChart,
    "DASHPlayerSimulator": DASHPlayerSimulator,
    "LiveStreamingDemo": LiveStreamingDemo,
    "VideoCodecComparison": VideoCodecComparison,
    "PythonSocketDemo": PythonSocketDemo,
    "EpollDemo": EpollDemo,
    "ConcurrentServerDemo": ConcurrentServerDemo,
    "ReactorDemo": ReactorDemo,
    "HighPerfServerDemo": HighPerfServerDemo,
    "SocketLayerDiagram": SocketLayerDiagram,
    "SocketBufferVisualizer": SocketBufferVisualizer,
    "ConnectionPoolDemo": ConnectionPoolDemo,
    "BPFExplorer": BPFExplorer,
    "PacketCaptureEngine": PacketCaptureEngine,
    "PortMuxSimulator": PortMuxSimulator,
    "CIATriad": CIATriad,
    "AESEncryptEngine": AESEncryptEngine,
    "BlockCipherModes": BlockCipherModes,
    "RSAModularExponentiation": RSAModularExponentiation,
    "HMACConstruction": HMACConstruction,
    "KeyManagementSystem": KeyManagementSystem,
    "CertificateValidator": CertificateValidator,
    "FirewallTCAMengine": FirewallTCAMengine,
    "IPsecSAengine": IPsecSAengine,
    "IDSDPIengine": IDSDPIengine,
    "ARPSpoofDetector": ARPSpoofDetector,
    "PortScannerSynEngine": PortScannerSynEngine,
    "SYNCookieDefense": SYNCookieDefense,
    "TrafficAnalysisEngine": TrafficAnalysisEngine,
    "NetFlowCollector": NetFlowCollector,
    "NetworkFaultDiagnosticEngine": NetworkFaultDiagnosticEngine,
    "WiFiMACController": WiFiMACController,
    "HandoverSimulation": HandoverSimulation,
    "CellularScheduler": CellularScheduler,
    "OFDMModulator": OFDMModulator,
    "CDMACodeVisualizer": CDMACodeVisualizer,
    "MultimediaTrafficAnalyzer": MultimediaTrafficAnalyzer,
    "WFQSchedulerSimulator": WFQSchedulerSimulator,
    "TokenBucketShaper": TokenBucketShaper,
    "DiffServClassifier": DiffServClassifier,
    "RTPPacketParser": RTPPacketParser,
    "WebSocketDemo": WebSocketDemo,
    "NetworkDelaySimulator": NetworkDelaySimulator,
    "BDPCalculator": BDPCalculator,
    "BandwidthMeasurementEngine": BandwidthMeasurementEngine,
    "QueuingSystemSimulator": QueuingSystemSimulator,
    "NetworkEnvironmentSimulator": NetworkEnvironmentSimulator,
    "ProtocolPerformanceCalculator": ProtocolPerformanceCalculator,
    "ProtocolPerformanceSimulator": ProtocolPerformanceSimulator,
    "CacheStrategyDemo": CacheStrategyDemo,
    "IPv6HeaderParser": IPv6HeaderParser,
    "IPv6AddressConverter": IPv6AddressConverter,
    "NDPStateDiagram": NDPStateDiagram,
    "SLAACProcessDiagram": SLAACProcessDiagram,
    "IoTArchExplorer": IoTArchExplorer,
    "MQTTQoSExplorer": MQTTQoSExplorer,
    "LoRaRangeCalculator": LoRaRangeCalculator,
    "EdgeSchedulerSimulator": EdgeSchedulerSimulator,
    "IoTBatteryCalculator": IoTBatteryCalculator,
    "SmartCityDashboard": SmartCityDashboard,
    "5GSliceExplorer": FiveGSliceExplorer,
    "FiveGSliceExplorer": FiveGSliceExplorer,
    "MobileIPTunnelEngine": MobileIPTunnelEngine,
    "ZoneFileEditor": ZoneFileEditor,
    "KnowledgeCheck": KnowledgeCheck,
    "ABRDemo": ABRDemo,
};

export function ContentRenderer({ html, moduleId }: ContentRendererProps) {
    const contentRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        if (!contentRef.current) return;

        // Add IDs to headings for scroll spy
        const headings = contentRef.current.querySelectorAll('h1, h2, h3');
        headings.forEach((heading) => {
            const text = heading.textContent || '';
            const id = text
                .toLowerCase()
                .trim()
                .replace(/\s+/g, '-')
                .replace(/[^\w\-\u4e00-\u9fa5]+/g, '')
                .replace(/\-\-+/g, '-');
            heading.id = id;
        });

        // Inject interactive components
        // Find and replace component markers (div with data-component attribute)
        const markers = contentRef.current.querySelectorAll('div[data-component]');
        markers.forEach((marker) => {
            const componentName = marker.getAttribute('data-component');

            if (componentName) {
                const Component = componentMap[componentName];

                if (Component) {
                    const container = document.createElement('div');
                    container.className = 'interactive-component-container my-8';
                    marker.replaceWith(container);

                    const root = createRoot(container);
                    root.render(<Component />);
                } else {
                    const placeholder = document.createElement('div');
                    placeholder.className = 'my-8 p-6 rounded-xl border border-dashed border-slate-300 dark:border-slate-600 bg-slate-50 dark:bg-slate-800/50 text-center';
                    placeholder.innerHTML = `
                        <div class="text-sm text-slate-400 dark:text-slate-500 font-medium mb-1">交互式组件</div>
                        <div class="text-xs text-slate-500 dark:text-slate-400">${componentName}</div>
                    `;
                    marker.replaceWith(placeholder);
                }
            }
        });
    }, [html, moduleId]);

    return (
        <div
            ref={contentRef}
            className="prose-content max-w-none [&>h1]:hidden"
            dangerouslySetInnerHTML={{ __html: html }}
        />
    );
}
